# GitHub automatically checks the code for pull requests to main

# Name of the GitHub Actions workflow
name: MIDAS CI
# Run this workflow if a pull request is made to main
on:
  pull_request:
    branches:
      - main

jobs:
  # Check MIDAS backend code
  backend-check:
    runs-on: ubuntu-latest
    # Run commands inside backend folder
    defaults:
      run:
        working-directory: backend

    steps:
      # Get the project code from GitHub
      - name: Get code
        uses: actions/checkout@v4
      # Install Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      # Install Python packages from requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
       # Run Ruff to check Python code quality
      - name: Run Ruff
        run: ruff check .